### PR TITLE
Feature/ht 36 space page stories

### PR DESCRIPTION
**Pull request by oetseli**
Essential space page fields in a basic layout. More to come with advanced referenced fields.

To test: drush cim and drush cr. Create a space and fill out the fields. You may also need to create some required taxonomy terms (price category, accessibility).

*NOTE:* This adds Display Suite and removes field_layout. You may need to disable field_layout by hand before importing. This is a known issue (core experimental field_layout being the culprit).

### CODE REVIEW

**Comment by oetseli** [comment]
I added some missing fields, page UI and dynamic display code. Otherwise this is still the same PR as it was when I created it.

This also includes commits for HT-58 and HT-52.

**Comment by ilmarioranen** [comment]
Currently getting this error on import:

 Import the listed configuration changes? (yes/no) [yes]:
 > yes

 [error]  TypeError: Argument 1 passed to {closure}() must implement interface Drupal\field_layout\Display\EntityDisplayWithLayoutInterface, instance of Drupal\Core\Entity\Entity\EntityViewDisplay given in {closure}() (line 34 of /app/web/core/modules/field_layout/field_layout.install) #0 [internal function]: {closure}(Object(Drupal\Core\Entity\Entity\EntityViewDisplay))
#1 /app/web/core/modules/field_layout/field_layout.install(37): array_map(Object(Closure), Array)
#2 [internal function]: field_layout_uninstall()
#3 /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(391): call_user_func_array('field_layout_un...', Array)
#4 /app/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(399): Drupal\Core\Extension\ModuleHandler->invoke('field_layout', 'uninstall')
#5 /app/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(91): Drupal\Core\Extension\ModuleInstaller->uninstall(Array, false)
#6 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(786): Drupal\Core\ProxyClass\Extension\ModuleInstaller->uninstall(Array, false)
#7 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(551): Drupal\Core\Config\ConfigImporter->processExtension('module', 'uninstall', 'field_layout')
#8 /app/web/core/lib/Drupal/Core/Config/ConfigImporter.php(488): Drupal\Core\Config\ConfigImporter->processExtensions(Array)
#9 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(237): Drupal\Core\Config\ConfigImporter->doSyncStep('processExtensio...', Array)
#10 /app/vendor/drush/drush/includes/drush.inc(232): Drush\Drupal\Commands\config\ConfigImportCommands->doImport(Object(Drupal\Core\Config\StorageComparer))
#11 /app/vendor/drush/drush/includes/drush.inc(223): drush_call_user_func_array(Array, Array)
#12 /app/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php(208): drush_op(Array, Object(Drupal\Core\Config\StorageComparer))
#13 [internal function]: Drush\Drupal\Commands\config\ConfigImportCommands->import(NULL, Array)
#14 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#15 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#16 /app/vendor/consolidation/annotated-command/src/CommandProcessor.php(150): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#17 /app/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(404): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#18 /app/vendor/symfony/console/Command/Command.php(264): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /app/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /app/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /app/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /app/vendor/drush/drush/src/Runtime/Runtime.php(112): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /app/vendor/drush/drush/src/Runtime/Runtime.php(41): Drush\Runtime\Runtime->doRun(Array)
#24 /app/vendor/drush/drush/drush.php(64): Drush\Runtime\Runtime->run(Array)
#25 /app/vendor/drush/drush/includes/preflight.inc(17): require('/app/vendor/dru...')
#26 phar:///usr/local/bin/drush/bin/drush.php(155): drush_main()
#27 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#28 {main}.

**Comment by oetseli** [comment]
Yes, uninstall field_layout first. Or now you might need to uninstall ds first. So:
drush pm-uninstall ds
drush pm-uninstall field_layout
drush cim

**Comment by ilmarioranen** [comment]
Thanks @oetseli , unstalling those first worked.

**Pull request merged**
