### PR TITLE
Feature/22 optime integration

### PR DESCRIPTION
**Pull request by ilmarioranen**
The integration branch has advanced some, and now also includes Otsos latest feature branches.
This branch also has lando config changes which are partially tied to the migration. To test those one needs to do "lando rebuild -s appserver", but thats not really needed (to run the migration).

The migration can be run with 
lando drush mim optime_integration --update

(Getting the latest migration changes is a bit more complicated though).
Anyway, this migration is still incomplete and test json has only 4 real spaces.

### CODE REVIEW

**Comment by ilmarioranen** [comment]
Dont review yet, a bunch of updates are on the way. Too bad HY linux servers are still down.

**Comment by ilmarioranen** [comment]
@oetseli 

Migrate is now using the full (though temporary) JSON (460+ spaces). 
Also drush cim -y might now get the updated migrate config version.
But.. most likely these actions are needed to get latest migrate working. I'm using this in ~/.bash_profile:

alias reload_optime_migration="lando drush mst optime_integration; lando drush mrs optime_integration;lando drush pm:uninstall -y migrate_optime_json migrate_tools migrate_plus; lando drush$

So then I can run the latest migration version with this command:
 reload_optime_migration; drush lando mim optime_integration --update

**Comment by oetseli** [comment]
438 created, 4 updated, 26 failed, 0 ignored

I'm getting this error 26 six times. Here are four examples:
`
K00301-521 | 1 | Array index missing, extraction failed. 
K00301-522 | 1 | Array index missing, extraction failed. 
K00301-524 | 1 | Array index missing, extraction failed.
K00301-526 | 1 | Array index missing, extraction failed.
`

**Comment by ilmarioranen** [comment]
Those errors are related to special space name/building name format, mainly the fact about 5% of the spaces dont seem to have actual name for their bulding, just an address. This is fixed in the last version of the importer, along with date and title related fields.

Also, now the importer url is by default pointing to the actual API, which only works on HY servers, not our local servers. So you need to override the url in settings.local.php (see settings.php for tips), to make it point to the static test json.

Meanwhile, I've setup crontabs on HY tilat servers, which run migrate imports periodically.

**Comment by ilmarioranen** [comment]
I committed a small improvement : building Id and street address are also copied to the building term from space node saving process (in case building has empty values for those). Will automate our processes a bit more.

Also, I think I've managed to find out the problem why dev server migration failed with SQL error. It seems uninstalling and reinstalling migrate module is one solution. www-admin has this alias which does that and more:
 reload_optime_migration
(You might want to copy the alias locally from ~/.bashrc

**Comment by ilmarioranen** [comment]
Or not.. I might have to uninstall some migrate SQL tables manually, arrr...

**Comment by ilmarioranen** [comment]
Devillä oli outo SQL-errori jonka sain vasta tänään aamulla korjattua manuaalisesti poistamalla vanhoja turhia tietokantatauluja. Sen jälkeen ajoin migraation tuoreella koodilla aitoa optime API:a vasten, mistä tuli n. 250 tila-nodea sisään onnistuneesti.

Tästä lähtien dev/stage/prod palvelimien www-admin -käyttäjän crontabissa on komento päivittää kamat 25min välein:

Fetch Optime data every 25mins. This interval could be made much smaller if/when the importer contains a dynamic

time filter, to limit the results to items that have updated within a short timeframe (such as last import time or last 24h).

#*/25 * * * * cd /var/www/opetustila-test.it.helsinki.fi/current/web/sites/default; /usr/lib/composer/vendor/bin/drush mim optime_integration --update

**Pull request merged**
